### ISSUE TITLE
Duplicate question count

### ISSUE THREAD

**Issue by lisp-ceo** [mchakravarty/welcome-to-fp-workshop#3]
Workshop Exercises :: Recursion :: Exercise 3 is duplicated.

https://github.com/mchakravarty/welcome-to-fp-workshop/blob/master/exercises/README.md#exercise-3-2
https://github.com/mchakravarty/welcome-to-fp-workshop/blob/master/exercises/README.md#exercise-3-3

**Comment by mchakravarty** [comment]
Fixed, thanks!
